// Code generated by "enumer -type=SpanKindEnum -linecomment -json -sql"; DO NOT EDIT.

package xopconst

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _SpanKindEnumName = "SERVERCLIENTPRODUCERCONSUMERINTERNAL"

var _SpanKindEnumIndex = [...]uint8{0, 6, 12, 20, 28, 36}

const _SpanKindEnumLowerName = "serverclientproducerconsumerinternal"

func (i SpanKindEnum) String() string {
	if i < 0 || i >= SpanKindEnum(len(_SpanKindEnumIndex)-1) {
		return fmt.Sprintf("SpanKindEnum(%d)", i)
	}
	return _SpanKindEnumName[_SpanKindEnumIndex[i]:_SpanKindEnumIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SpanKindEnumNoOp() {
	var x [1]struct{}
	_ = x[SpanKindServer-(0)]
	_ = x[SpanKindClient-(1)]
	_ = x[SpanKindProducer-(2)]
	_ = x[SpanKindConsumer-(3)]
	_ = x[SpanKindInternal-(4)]
}

var _SpanKindEnumValues = []SpanKindEnum{SpanKindServer, SpanKindClient, SpanKindProducer, SpanKindConsumer, SpanKindInternal}

var _SpanKindEnumNameToValueMap = map[string]SpanKindEnum{
	_SpanKindEnumName[0:6]:        SpanKindServer,
	_SpanKindEnumLowerName[0:6]:   SpanKindServer,
	_SpanKindEnumName[6:12]:       SpanKindClient,
	_SpanKindEnumLowerName[6:12]:  SpanKindClient,
	_SpanKindEnumName[12:20]:      SpanKindProducer,
	_SpanKindEnumLowerName[12:20]: SpanKindProducer,
	_SpanKindEnumName[20:28]:      SpanKindConsumer,
	_SpanKindEnumLowerName[20:28]: SpanKindConsumer,
	_SpanKindEnumName[28:36]:      SpanKindInternal,
	_SpanKindEnumLowerName[28:36]: SpanKindInternal,
}

var _SpanKindEnumNames = []string{
	_SpanKindEnumName[0:6],
	_SpanKindEnumName[6:12],
	_SpanKindEnumName[12:20],
	_SpanKindEnumName[20:28],
	_SpanKindEnumName[28:36],
}

// SpanKindEnumString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SpanKindEnumString(s string) (SpanKindEnum, error) {
	if val, ok := _SpanKindEnumNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SpanKindEnumNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SpanKindEnum values", s)
}

// SpanKindEnumValues returns all values of the enum
func SpanKindEnumValues() []SpanKindEnum {
	return _SpanKindEnumValues
}

// SpanKindEnumStrings returns a slice of all String values of the enum
func SpanKindEnumStrings() []string {
	strs := make([]string, len(_SpanKindEnumNames))
	copy(strs, _SpanKindEnumNames)
	return strs
}

// IsASpanKindEnum returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SpanKindEnum) IsASpanKindEnum() bool {
	for _, v := range _SpanKindEnumValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SpanKindEnum
func (i SpanKindEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SpanKindEnum
func (i *SpanKindEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SpanKindEnum should be a string, got %s", data)
	}

	var err error
	*i, err = SpanKindEnumString(s)
	return err
}

func (i SpanKindEnum) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *SpanKindEnum) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of SpanKindEnum: %[1]T(%[1]v)", value)
	}

	val, err := SpanKindEnumString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
